<?php
namespace ResourceCatalog\Model;

interface IUserGroupIdentify
{
    const IDENTIFY = array(
        IUserGroup::ID['NULL'] => 'NULL',
        IUserGroup::ID['SFGW'] => 'SFGW',
        IUserGroup::ID['SCZJ'] => 'SCZJ',
        IUserGroup::ID['SYBJ'] => 'SYBJ',
        IUserGroup::ID['SRSJ'] => 'SRSJ',
        IUserGroup::ID['SWSJKW'] => 'SWSJKW',
        IUserGroup::ID['SFY'] => 'SFY',
        IUserGroup::ID['SJYJ'] => 'SJYJ',
        IUserGroup::ID['SZWFWJ'] => 'SZWFWJ',
        IUserGroup::ID['SWJ'] => 'SWJ',
        IUserGroup::ID['SSJJ'] => 'SSJJ',
        IUserGroup::ID['SGAJ'] => 'SGAJ',
        IUserGroup::ID['SSFJ'] => 'SSFJ',
        IUserGroup::ID['SGBDST'] => 'SGBDST',
        IUserGroup::ID['SGYHXXHJ'] => 'SGYHXXHJ',
        IUserGroup::ID['SZJJ'] => 'SZJJ',
        IUserGroup::ID['STJJ'] => 'STJJ',
        IUserGroup::ID['SZFB'] => 'SZFB',
        IUserGroup::ID['SSCJDGLJ'] => 'SSCJDGLJ',
        IUserGroup::ID['SHBJ'] => 'SHBJ',
        IUserGroup::ID['SJCY'] => 'SJCY',
        IUserGroup::ID['SGGZYJYZX'] => 'SGGZYJYZX',
        IUserGroup::ID['SJRB'] => 'SJRB',
        IUserGroup::ID['SNMJ'] => 'SNMJ',
        IUserGroup::ID['SSWJ'] => 'SSWJ',
        IUserGroup::ID['SKJJ'] => 'SKJJ',
        IUserGroup::ID['SCXGHJSJ'] => 'SCXGHJSJ',
        IUserGroup::ID['SMZJ'] => 'SMZJ',
        IUserGroup::ID['SWMB'] => 'SWMB',
        IUserGroup::ID['SYJGLJ'] => 'SYJGLJ',
        IUserGroup::ID['SRMYH'] => 'SRMYH',
        IUserGroup::ID['SZRZYJ'] => 'SZRZYJ',
        IUserGroup::ID['SLCJ'] => 'SLCJ',
        IUserGroup::ID['SZGH'] => 'SZGH',
        IUserGroup::ID['SJTJ'] => 'SJTJ',
        IUserGroup::ID['SGZW'] => 'SGZW',
        IUserGroup::ID['SGSL'] => 'SGSL',
        IUserGroup::ID['JZQ'] => 'JZQ',
        IUserGroup::ID['QYQ'] => 'QYQ',
        IUserGroup::ID['QAX'] => 'QAX',
        IUserGroup::ID['YFX'] => 'YFX',
        IUserGroup::ID['WAX'] => 'WAX',
        IUserGroup::ID['XQX'] => 'XQX',
        IUserGroup::ID['JSX'] => 'JSX',
        IUserGroup::ID['THX'] => 'THX',
        IUserGroup::ID['AFX'] => 'AFX',
        IUserGroup::ID['XJX'] => 'XJX',
        IUserGroup::ID['SCX'] => 'SCX',
        IUserGroup::ID['YXX'] => 'YXX',
        IUserGroup::ID['JGSS'] => 'JGSS',
        IUserGroup::ID['JKQ'] => 'JKQ',
        IUserGroup::ID['LLXQ'] => 'LLXQ',
        IUserGroup::ID['SFL'] => 'SFL'
    );
}
