<?php
namespace ResourceCatalog\Model;

interface IUserGroup extends IUserGroupIdentify
{
    const ID = array(
        'NULL' => 0,
        'SFGW' => 1,
        'SCZJ' => 2,
        'SYBJ' => 3,
        'SRSJ' => 4,
        'SWSJKW' => 5,
        'SFY' => 6,
        'SJYJ' => 7,
        'SZWFWJ' => 8,
        'SWJ' => 9,
        'SSJJ' => 10,
        'SGAJ' => 11,
        'SSFJ' => 12,
        'SGBDST' => 13,
        'SGYHXXHJ' => 14,
        'SZJJ' => 15,
        'STJJ' => 16,
        'SZFB' => 17,
        'SSCJDGLJ' => 18,
        'SHBJ' => 19,
        'SJCY' => 20,
        'SGGZYJYZX' => 21,
        'SJRB' => 22,
        'SNMJ' => 23,
        'SSWJ' => 24,
        'SKJJ' => 26,
        'SCXGHJSJ' => 25,
        'SMZJ' => 27,
        'SWMB' => 28,
        'SYJGLJ' => 29,
        'SRMYH' => 30,
        'SZRZYJ' => 31,
        'SLCJ' => 32,
        'SZGH' => 33,
        'SJTJ' => 34,
        'SGZW' => 35,
        'SGSL' => 36,
        'JZQ' => 37,
        'QYQ' => 38,
        'QAX' => 39,
        'YFX' => 40,
        'WAX' => 41,
        'XQX' => 42,
        'JSX' => 43,
        'THX' => 44,
        'AFX' => 45,
        'XJX' => 46,
        'SCX' => 47,
        'YXX' => 48,
        'JGSS' => 49,
        'JKQ' => 50,
        'LLXQ' => 51,
        'SFL' => 52
    );
}
